dll:
  - Sources/**/*
  - Sources/*

tool:
  - Tools/**/*
  - Tools/*

xml:
  - Assets/**/*.xml
  - Assets/*.xml

text:
  - Assets/XML/GameText/**/*
  - Assets/XML/GameText/*
  - Assets/Modules/**/*Text*.xml
  - Assets/Modules/*Text*.xml

python:
  - Assets/Python/**/*
  - Assets/Python/*
  - PrivateMaps/*.py

art:
  - UnpackedArt/**/*
  - UnpackedArt/*
  - ArtSource/**/*
  - ArtSource/*
  - Assets/art/**/*
  - Assets/art/*

audio:
  - Assets/Sounds/**/*
  - Assets/Sounds/*
