#pragma once

#define SLABEL(name,val) (std::string)(name + ">" + val + "?")
#define OLABEL(name,val) name << ">" << val << "?"

#define CSTR(x) x.c_str()

#define ICONKEY "icon"

#define FILEFOOTER "\n\n## File automatically generated by Caveman2Cosmos for RPC Integration. Will be deleted after closing civ4 or disabling RPC in Game Settings. ##"

struct S_RPCDATA {
	int start;
	std::string state;
	std::string details;
	std::string igstate;
	bool stop;
};