#pragma once

#ifndef GlobalDefines_h__
#define GlobalDefines_h__

#define DO_FOR_EACH_INT_GLOBAL_DEFINE(DO) \
	DO(AT_WAR_CULTURE_ANGER_MODIFIER) \
	DO(CITY_AIR_UNIT_CAPACITY) \
	DO(CONSCRIPT_ANGER_DIVISOR) \
	DO(CONSCRIPT_MIN_CITY_POPULATION) \
	DO(CONSCRIPT_MIN_CULTURE_PERCENT) \
	DO(CONSCRIPT_POPULATION_PER_COST) \
	DO(CULTURE_PERCENT_ANGER) \
	DO(FREE_CITY_ADJACENT_CULTURE) \
	DO(FREE_CITY_CULTURE) \
	DO(INITIAL_CITY_POPULATION) \
	DO(MAXED_BUILDING_GOLD_PERCENT) \
	DO(MAXED_PROJECT_GOLD_PERCENT) \
	DO(MAX_TRADE_ROUTES) \
	DO(MAXED_UNIT_GOLD_PERCENT) \
	DO(NO_MILITARY_PERCENT_ANGER) \
	DO(PLOT_VISIBILITY_RANGE) \
	DO(RELIGION_PERCENT_ANGER) \
	DO(RUINS_IMPROVEMENT) \
	DO(WE_LOVE_THE_KING_POPULATION_MIN_POPULATION) \
	DO(WE_LOVE_THE_KING_RAND) \
	//DO() \
	DO() \
	DO() \
	DO() \
	DO() \
	DO() \
	DO() \
	DO() \
	DO() \
	DO() \
	DO() \
	DO() \

#endif