## BugUnitNameOptionsTab
##
## Tab for the BUG Unit Name Options.
##
## Copyright (c) 2007-2008 The BUG Mod.
##
## Author: Ruff_Hi

import BugOptionsTab

class BugUnitNameOptionsTab(BugOptionsTab.BugOptionsTab):
	"BUG Unit Name Options Screen Tab"

	def __init__(self, screen):
		BugOptionsTab.BugOptionsTab.__init__(self, "UnitNaming", "Unit Naming")

	def create(self, screen):
		tab = self.createTab(screen)
		panel = self.createMainPanel(screen)
		column = self.addOneColumnLayout(screen, panel)

		left, center, right = self.addThreeColumnLayout(screen, column, "Options")

		self.addCheckbox(screen, left, "UnitNaming__Enabled")
		self.addCheckbox(screen, center, "MiscHover__UpdateUnitNameOnUpgrade")
		self.addCheckbox(screen, right, "UnitNaming__UseAdvanced")

		columnL, columnR = self.addTwoColumnLayout(screen, column, "UnitNaming")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Default")
		# self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_AIR")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL")
		# self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_AIR_RECON")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARCHER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ASSAULT_MECH")
		# self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIOLOGICAL")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BOMBERS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CLONES")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_DREADNOUGHT")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_DIESEL_SHIPS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_DOOM")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_EARLY_BOMBERS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_EARLY_FIGHTERS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SPY")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GUN")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_HELICOPTER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_HERO")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_HITECH")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_HUNTER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_JET_FIGHTERS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MELEE")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MISSILE")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNTED")
		# self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_NAVAL")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_None")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_NANITE")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_NUCLEAR_SHIPS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SUBMARINE")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_DESTROYER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CRUISER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BATTLESHIP")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_PIRATE")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RECON")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ROBOT")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SETTLER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIEGE")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_STEALTH")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_STEAM_SHIPS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SUPERSONIC_PLANES")
		# self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SPY")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_TRACKED")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WHEELED")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WOODEN_SHIPS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WORKER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_COMBAT_WORKER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CANINE")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_COMBATANT")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CRIMINAL")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_EXECUTIVE")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_FELINE")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SEA_WORKER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_EXPLORER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_THROWING")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_LAW_ENFORCEMENT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIZE_FINE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIZE_DIMINUTIVE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIZE_TINY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIZE_SMALL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIZE_MEDIUM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIZE_LARGE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIZE_HUGE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIZE_GARGANTUAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIZE_COLOSSAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SPEED_SLOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SPEED_FAST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_COLLISION_BLUNT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_COLLISION_PIERCING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SELF_DETONATION")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_TRAMPLE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_BLUNT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_PIERCING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_SLASHING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_FIRE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_ELECTRICITY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_FROST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_POISON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_THERMONUCLEAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_EXPLOSIVE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_DISINTIGRATION")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_LASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_HEAT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_SONIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_PSYCH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_CYBER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_BIOLOGICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_H2H_EMP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_BLUNT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_PIERCING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_SLASHING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_FIRE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_ELECTRICITY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_FROST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_POISON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_THERMONUCLEAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_EXPLOSIVE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_DISINTIGRATION")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_LASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_HEAT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_SONIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_PSYCH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_CYBER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_BIOLOGICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_SIDEARM_EMP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_BLUNT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_PIERCING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_SLASHING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_FIRE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_ELECTRICITY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_FROST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_POISON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_THERMONUCLEAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_EXPLOSIVE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_DISINTIGRATION")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_LASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_HEAT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_SONIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_PSYCH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_CYBER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_BIOLOGICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_DISTANCE_EMP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_BLUNT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_PIERCING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_SLASHING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_FIRE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_ELECTRICITY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_FROST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_POISON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_THERMONUCLEAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_EXPLOSIVE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_DISINTIGRATION")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_LASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_HEAT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_SONIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_PSYCH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_CYBER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_BIOLOGICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_BACKUP_EMP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_BLUNT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_PIERCING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_SLASHING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_FIRE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_ELECTRICITY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_FROST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_POISON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_THERMONUCLEAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_EXPLOSIVE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_DISINTIGRATION")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_LASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_HEAT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_SONIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_PSYCH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_CYBER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_BIOLOGICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACK_FORM_A2G_EMP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_METHOD_HAND_TO_HAND_ONLY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_METHOD_DISTANCE_ONLY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_METHOD_DISTANCE_PRIMARY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_METHOD_DISTANCE_SECONDARY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_METHOD_WARHEAD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_H2H_SINGLE_HAND_ONLY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_H2H_PRIMARY_PLUS_SECONDARY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_H2H_SINGLE_PLUS_SHIELD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_H2H_TWO_HANDED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_H2H_TWO_HANDED_PLUS_SHIELD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_H2H_VEHICULAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_SIDEARM_SINGLE_HAND_ONLY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_SIDEARM_PRIMARY_PLUS_SECONDARY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_SIDEARM_SINGLE_PLUS_SHIELD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_SIDEARM_TWO_HANDED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_SIDEARM_TWO_HANDED_PLUS_SHIELD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_DIST_SINGLE_HAND_ONLY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_DIST_PRIMARY_PLUS_SECONDARY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_DIST_SINGLE_PLUS_SHIELD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_DIST_TWO_HANDED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_DIST_TWO_HANDED_PLUS_SHIELD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_DIST_VEHICULAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_BACKUP_SINGLE_HAND_ONLY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_BACKUP_PRIMARY_PLUS_SECONDARY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_BACKUP_SINGLE_PLUS_SHIELD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_BACKUP_TWO_HANDED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_STYLE_BACKUP_TWO_HANDED_PLUS_SHIELD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_FIST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_ROCK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_CLUB")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_OAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_FLAIL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_MACE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_AXE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_HAMMER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_KNIFE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_BAYONETTE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_SHORT_BLADE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_LONG_BLADE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_SHORT_POLEARM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_LONG_POLEARM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_STAFF")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_MARTIAL_ART")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_HANDGUN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_RIFLE_BUTT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_HYDRAULIC_APPENDAGE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_CROWBAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_FLAMETHROWER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_LASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_TASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_SPRAY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_ENERGY_GLOVES")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_H2H_EMP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_FIST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_ROCK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_CLUB")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_OAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_FLAIL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_MACE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_AXE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_HAMMER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_KNIFE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_BAYONETTE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_SHORT_BLADE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_LONG_BLADE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_SHORT_POLEARM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_LONG_POLEARM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_STAFF")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_MARTIAL_ART")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_HANDGUN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_RIFLE_BUTT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_HYDRAULIC_APPENDAGE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_CROWBAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_FLAMETHROWER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_LASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_TASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_SPRAY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_ENERGY_GLOVES")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_SIDEARM_EMP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_ROCK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_CLUB")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_AXE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_HAMMER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_KNIFE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_BLOWGUN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_SLING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_JAVELIN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_BOOMERANG")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_BOLA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_MARTIAL_ART")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_DYNAMITE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_EXPLOSIVE_FLASK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_GRENADE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_LIGHT_CROSSBOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_HEAVY_CROSSBOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_REPEATING_CROSSBOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_SHORTBOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_LONGBOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_HANDGUN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_RIFLE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_SEMI_AUTOMATIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_FULLY_AUTOMATIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_LASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_ION")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_FROST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_ELECTRICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_FLAME")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_HEAT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_SONIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_EMP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_BALLISTA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_LAUNCHED_STONE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_FIREWORKS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_CANNONBALL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_SHELLFIRE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_SHORT_RANGE_MISSILE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_MEDIUM_RANGE_MISSILE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_LONG_RANGE_MISSILE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DIST_TORPEDO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_ROCK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_CLUB")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_AXE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_HAMMER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_KNIFE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_BLOWGUN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_SLING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_JAVELIN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_BOOMERANG")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_BOLA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_MARTIAL_ART")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_DYNAMITE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_EXPLOSIVE_FLASK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_GRENADE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_LIGHT_CROSSBOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_HEAVY_CROSSBOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_REPEATING_CROSSBOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_SHORTBOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_LONGBOW")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_HANDGUN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_RIFLE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_SEMI_AUTOMATIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_FULLY_AUTOMATIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_LASER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_ION")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_FROST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_ELECTRICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_FLAME")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_HEAT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_SONIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_EMP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_BALLISTA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_LAUNCHED_STONE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_FIREWORKS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_CANNONBALL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_SHELLFIRE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_SHORT_RANGE_MISSILE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_MEDIUM_RANGE_MISSILE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_LONG_RANGE_MISSILE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_BACKUP_TORPEDO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DETONATE_DYNAMITE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DETONATE_GUIDED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DETONATE_CHEMICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DETONATE_BIOLOGICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DETONATE_RADIOACTIVE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_DETONATE_PSYCH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_A2G_BOMBS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_A2G_GUIDED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_A2G_RADIOACTIVE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_A2G_CHEMICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_A2G_BIOLOGICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_A2G_SHORT_RANGE_MISSILE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_A2G_MEDIUM_RANGE_MISSILE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_A2G_LONG_RANGE_MISSILE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WEAPON_A2G_TORPEDO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_LIGHT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MEDIUM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_HEAVY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MODERN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_VEHICULAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_NAVAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_AIRCRAFT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_SPACECRAFT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_BUCKLER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_SMALL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_LARGE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_TOWER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_ENERGY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_VENEMOUS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_TOUGH_HIDE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_THICK_SKINNED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_HARD_PLATED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_SHELLED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_SCRATCH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_NIP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_PECK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_SHARP_CLAWED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_SHARP_TOOTHED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_SHARP_HORNED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_HEAD_BUTT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_POWER_KICK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_POUNCE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_PUMMEL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_CHASING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_TAIL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_STOMP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_BURROWING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_CHARGING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_FAST_REFLEXES")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_FLEEING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_HIDING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_CAMOFLAGED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_ROARING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_WARNING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_REPELLENT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_SUBMERGE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_TREECLIMBING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_CONSTRICT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_RAGING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_PACK_HUNTER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_HERDING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_KEEN_SENSES")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_FECAL_FLINGING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_COMBAT_DEVOUR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_INVERTEBRATE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_FISH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_AMPHIBIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_REPTILE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_BIRD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_MAMMAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANIMAL_INSECT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_INVERTEBRATE_CRUSTACEAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_INVERTEBRATE_MOLLUSK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_FISH_RAY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_FISH_SHARK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_FISH_BONEY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_AMPHIBIAN_FROG")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_AMPHIBIAN_SALAMANDER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_REPTILE_TURTLE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_REPTILE_SNAKE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_REPTILE_LIZARD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_REPTILE_CROCODILIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_RATITE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_PENGUIN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_SEABIRD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_WATERFOWL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_GAMEBIRD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_CORVID")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_PARROT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_PIGEON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_KINGFISHER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_SONGBIRD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BIRD_RAPTOR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_MONOTREME")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_MARSUPIAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_ANTEATER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_BAT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_PRIMATE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_URSINE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_RACCOON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_MUSTELIDAE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_HYENA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_PINNIPED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_WHALE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_SIRENIA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_PACHYDERM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_EQUINE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_TAPIR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_RHINO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_SWINE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_HIPPO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_CAMELID")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_CERVID")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_GIRAFFE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_BOVINE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_ANTELOPE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_GOAT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_LAGOMORPH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MAMMAL_RODENT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_TRANSPORT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SWARM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RUFFIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOTILITY_FOOT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOTILITY_RIDING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOTILITY_ANIMAL_DRAWN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOTILITY_DRIVING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOTILITY_PILOTING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOTILITY_AERIAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOTILITY_HOVERING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOTILITY_NAVAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOTILITY_UNMANNED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_STRIKE_TEAM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ROCKET_LAUNCHER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_HOVERCRAFT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANTIGRAV_CRAFT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BALLOON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ORBITAL_AIRCRAFT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_EARLY_SPACESHIP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SOLAR_SAIL_SPACESHIP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_NUCLEAR_SPACESHIP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ANTIMATTER_SPACESHIP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WORMHOLE_SPACESHIP")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ENTERTAINER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ADMINISTRATOR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_PRODIGY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIEGE_DEFENSIVE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIEGE_GATECRASHER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIEGE_FIELD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIEGE_URBAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIEGE_WOODEN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIEGE_GUNPOWDER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIEGE_ROCKETRY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SIEGE_ENERGY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SPECIES_HUMAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SPECIES_NEANDERTHAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SPECIES_ALIEN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SPECIES_AI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ERA_PREHISTORIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ERA_ANCIENT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ERA_CLASSICAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ERA_MEDIEVAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ERA_RENAISSANCE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ERA_INDUSTRIAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ERA_ATOMIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ERA_TRANSHUMAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ERA_GALACTIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ERA_FUTURE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_HORSE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_MULE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_CAMEL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_LLAMA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_ELEPHANT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_GIRAFFE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_BEAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_DEER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_BISON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_RHINO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_MAMMOTH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_MOUNT_ZEBRA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ASSISTED_DOG")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ASSISTED_BUFFALO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ASSISTED_MULE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ASSISTED_ELEPHANT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ASSISTED_MAMMOTH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ASSISTED_LLAMA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ASSISTED_CAMEL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_JUDAISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_CHRISTIANITY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_ISLAM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_HINDUISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_BUDDHISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_CONFUCIANISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_TAOISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_ZOROASTRIANISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_BAHAI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_ANDEANISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_NGAIISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_KEMETISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_HELLENISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_NAGHUALISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_MORMON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_YORUBA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_TENGRIISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_SHINTO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_VOODOO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_ASATRU")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_DRUIDIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_SHAMANISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_MESOPOTAMIANISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_SCIENTOLOGY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_JAINISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_SIKHISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_RELIGION_CANAANISM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ABORIGINE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_AINU")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_AKA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_AMERICAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_APACHE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ARABIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ARAWAK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ARMENIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ASSYRIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ATOMPUNK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_AUSTRALIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_AUSTRIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_AZTEC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BABYLONIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BANDANESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BASQUE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BELGIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BENGALI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BENIN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BERBER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BIOPUNK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BRAZILIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BURMESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_BYZANTINE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CANADIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CANTONESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CARIB")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CARTHAGINIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CELTIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CETACEA_SAPIEN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CEYLONESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CHAM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CHEROKEE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CHEYENNE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CHINESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CHOLA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CHUMASH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CLOCKPUNK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_COMANCHE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CONFEDERATES")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CREE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CUBAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_CYBERPUNK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_DAHOMEY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_DENE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_DIESELPUNK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_DUTCH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_EGYPTIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ENGLISH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ETHIOPIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_FRANKS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_FRENCH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_FULANI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_GERMAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_GOTH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_GREEK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_HAIDA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_HAITIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_HAUSA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_HERERO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_HITTITE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_HOLY_ROMAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_HOPI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_HUN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_HUNGARIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_HURON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_INCAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_INDIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_INDONESIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_INUIT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_IRISH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_IROQUOIS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ISRAELI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ITALIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_JAPANESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_JIVARO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_JOMON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_JOSEON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_KANEM_BORNU")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_KHMER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_KLAMATH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_KONGOLESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_KOREAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_LUBA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MALINESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MANCHURIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MAORI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MAPUCHE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MASAI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MAYAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MERINA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MEXICAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MINOAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MOCHE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MONGOLIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MOROCCAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MUGHAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_MUTAPA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_NAVAJO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_NAZCA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_NEANDERTHAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_NEPALESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_NEW_ZEALAND")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_NOOTKA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_NUBIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_OLMEC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_OTTOMAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_PAKISTANI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_PAPUAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_PARTHIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_PERSIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_PHOENICIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_POLISH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_POLYNESIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_PORTUGUESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_PRUSSIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_QUECHUA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_RAPA_NUI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ROMAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_RUSSIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SASSANIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SAXON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SCOTTISH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SCYTHIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SEMINOLE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SHANG")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SIAMESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SIBERIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SIOUX")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SOMALI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SOUTH_AFRICAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SPANISH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SPARTAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_STEAMPUNK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SUMERIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SWAHILI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SWAZI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SWISS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_SYRIAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_TAMIL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_THAI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_TIBETAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_TOLTEC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_TROJAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_TUAREG")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_TUPI")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_TURKMEN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_UIGHUR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_VENEZUELAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_VIETNAMESE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_VIKING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_WELSH")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_XIONGNU")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_YAMATO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ZAPOTEC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CULTURE_ZULU")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_WILD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SUBDUED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_IDEA")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_BALLISTIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CAPTAIN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ATTACHE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CAPTIVE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_SOLO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_PARTY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_SQUAD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_COMPANY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_BATTALION")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_FORCES")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_CLAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_HORDE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_MULTITUDES")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_MILLIONS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_BILLIONS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GROUP_TRILLIONS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_PADDED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_WOVEN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_HIDE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_WOOD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_CHAIN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_RING")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_SCALE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_BANDED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_PLATE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_VEST")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_BOMBSUIT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_EXOSKELETAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_GELL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_BELT")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_EXTERIOR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_TYPE_CHARGED")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_BARK")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_BAMBOO")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_RATTAN")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_FABRIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_SOFT_LEATHER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_HARD_LEATHER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_COPPER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_BRONZE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_IRON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_BONE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_STEEL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_CERAMIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_KEVLAR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_POLY")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_TWARON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_GELL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_ALUMINUM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_TITANIUM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_URANIUM")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_PLASTIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_COMPOSITE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_ARMOR_MATERIAL_NANOFIBER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_MATERIAL_WOOD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_MATERIAL_BONE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_MATERIAL_HARD_LEATHER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_MATERIAL_COPPER")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_MATERIAL_BRONZE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_MATERIAL_IRON")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_MATERIAL_STEEL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_MATERIAL_CERAMIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_MATERIAL_PLASTIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHIELD_MATERIAL_FIELD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_QUALITY_PATHETIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_QUALITY_INFERIOR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_QUALITY_POOR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_QUALITY_MEDIOCRE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_QUALITY_STANDARD")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_QUALITY_SUPERIOR")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_QUALITY_EXCEPTIONAL")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_QUALITY_ELITE")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_QUALITY_EPIC")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_PROMOTED_CAUTIOUS")
		#~ self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_PROMOTED_STALL")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CORVETTE")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CUTTER")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SWARMSHIP")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_JET_SHIPS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_SHOCKWAVE_SHIPS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_DROID_SHIPS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_GRAVITY_DRIVE_SHIPS")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_NAVAL_COMBATANT")
		self.addTextEdit(screen, columnL, columnR, "UnitNaming__Combat_CARRIER")


