## Sid Meier's Civilization 4
## Copyright Firaxis Games 2005

# Enum for screens...

from CvPythonExtensions import CivilopediaPageTypes

DOMESTIC_ADVISOR = 0
REWARD_SCREEN = 1
DAWN_OF_MAN = 2
TECH_CHOOSER = 3
FOREIGN_ADVISOR = 4
FINANCE_ADVISOR = 5
WONDER_MOVIE_SCREEN = 6
RELIGION_SCREEN = 7
INTRO_MOVIE_SCREEN = 8
CIVICS_SCREEN = 9
DIPLOMACY_SCREEN = 10
OPTIONS_SCREEN = 11
TECH_SPLASH = 12
REPLAY_SCREEN = 13
MILITARY_ADVISOR = 14
VICTORY_SCREEN = 15
TOP_CIVS = 16
TUTORIAL_SCREEN = 17
INFO_SCREEN = 18
ERA_MOVIE_SCREEN = 19
ADVISOR_SCREEN = 20
HALL_OF_FAME = 21
DAN_QUAYLE_SCREEN = 22
WORLDBUILDER_SCREEN = 23
WORLDBUILDER_DIPLOMACY_SCREEN = 24
VICTORY_MOVIE_SCREEN = 25
UN_SCREEN = 26
ESPIONAGE_ADVISOR = 27
SPACE_SHIP_SCREEN = 28
CORPORATION_SCREEN = 29

REVOLUTION_WATCH_ADVISOR = 30

BUILD_LIST_SCREEN = 31

GREAT_PEOPLE_SCREEN = 40

FORGETFUL_SCREEN = 81
TIMEKEEPER = 82
GAMEFONT_SCREEN = 83

MAIN_INTERFACE = 99
DEBUG_INFO_SCREEN = 100
BUGOPTIONSSCREEN = 101
STRATEGY_OVERLAY_SCREEN = 102

PEDIA = 200

MAD_NUKES_MANAGER = 4203

C2C_INITIAL_OPTIONS_SCREEN = 4300
C2C_NATIONAL_ADVISOR_SCREEN = 4301